// lib/data/local/hive_service.dart

import 'package:hive/hive.dart';
import 'package:hive_flutter/hive_flutter.dart';

import '../../model/todo_model.dart';


/// LOCAL DATA SOURCE - HiveService
///
/// Handles all local database operations using Hive
///
/// Responsibilities:
/// - Initialize Hive database
/// - CRUD operations on local storage
/// - Data persistence management
/// - Provide fast, offline-first data access
///
/// Business Logic:
/// - All data is stored locally in a Hive box
/// - Provides synchronous access to cached data
/// - No network dependency
class HiveService {
  static const String _todoBoxName = 'todos';
  Box<TodoModel>? _todoBox;

  /// Initialize Hive and open the todos box
  /// Must be called before any other operations
  Future<void> init() async {
    await Hive.initFlutter();

    // Register adapter if not already registered
    // TypeAdapter is generated by build_runner
    if (!Hive.isAdapterRegistered(0)) {
      Hive.registerAdapter(TodoModelAdapter());
    }

    // Open the todos box for read/write operations
    _todoBox = await Hive.openBox<TodoModel>(_todoBoxName);
  }

  /// Get all todos from local storage
  /// Returns: List of all stored todos
  List<TodoModel> getAllTodos() {
    return _todoBox?.values.toList() ?? [];
  }

  /// Save single todo to local storage
  /// Uses todo.id as the key for easy retrieval
  Future<void> saveTodo(TodoModel todo) async {
    await _todoBox?.put(todo.id, todo);
  }

  /// Save multiple todos in a single operation (bulk save)
  /// More efficient than saving one by one
  /// Used when syncing from API
  Future<void> saveAllTodos(List<TodoModel> todos) async {
    final Map<String, TodoModel> todoMap = {
      for (var todo in todos) todo.id: todo
    };
    await _todoBox?.putAll(todoMap);
  }

  /// Update existing todo
  /// Same as saveTodo since Hive uses upsert logic
  Future<void> updateTodo(TodoModel todo) async {
    await _todoBox?.put(todo.id, todo);
  }

  /// Delete todo by id
  Future<void> deleteTodo(String id) async {
    await _todoBox?.delete(id);
  }

  /// Clear all todos from local storage
  /// Used when refreshing from API
  Future<void> clearAllTodos() async {
    await _todoBox?.clear();
  }

  /// Check if local storage is empty
  /// Used to determine if we need to fetch from API
  bool isEmpty() {
    return _todoBox?.isEmpty ?? true;
  }

  /// Get total count of stored todos
  int getTodoCount() {
    return _todoBox?.length ?? 0;
  }
}